# Created with WinGet Releaser using komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: MartiCliment.UniGetUI.Pre-Release
PackageVersion: 3.3.1-beta1-msix
PackageLocale: en-US
Publisher: Martí Climent
PublisherUrl: https://github.com/marticliment
PublisherSupportUrl: https://github.com/marticliment/UniGetUI/issues
PackageName: UniGetUI (formerly WingetUI) - Pre-Release
PackageUrl: https://github.com/marticliment/UniGetUI
License: MIT
LicenseUrl: https://github.com/marticliment/UniGetUI/blob/HEAD/LICENSE
ShortDescription: A better UI for your package managers
Tags:
- chocolatey
- cli
- npm
- package
- package-manager
- pip
- scoop
- unigetui
- windows
- windows-10
- windows-11
- winget
ReleaseNotes: |-
  Changes
  - Migrate UniGetUI installation to MSIX, to be able to have executable integrity (guaranteed by Windows and the Appx/Msix infrastructure)
  - This does NOT mean that UniGetUI is now packaged. UniGetUI will continue working unpackaged.
  - Depending on how this beta release goes, and the following ones continue, All users will be migrated to MSIX, or these changes will be reverted
  UniGetUI.Installer.exe SHA256: A09075F3D766C610EAC949DC79F8B3D21BD0D6E996BC0FA7B24A908EFE5A7192
  UniGetUI.x64.Msix SHA256: 2A5A9FDF527F3DADD6B0F910047944EE47187995A69CBC87D077965D79DE0F10
  UniGetUI.x64.zip SHA256: A4DCCCB0ED04A960DB61A83EE35A8315A3D95D8CC8C0C6B6AFAFC639C45D9F91
ReleaseNotesUrl: https://github.com/marticliment/UniGetUI/releases/tag/3.3.1-beta1-msix
ManifestType: defaultLocale
ManifestVersion: 1.10.0
