# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: MartiCliment.UniGetUI
PackageVersion: 3.3.4
PackageLocale: en-US
Publisher: Martí Climent
PublisherUrl: https://github.com/marticliment/UniGetUI
PublisherSupportUrl: https://github.com/marticliment/UniGetUI/issues
Author: Martí Climent
PackageName: UniGetUI (formerly WingetUI)
PackageUrl: https://github.com/marticliment/UniGetUI
License: MIT
LicenseUrl: https://github.com/marticliment/UniGetUI/blob/HEAD/LICENSE
Copyright: Copyright (c) 2024 Martí Climent
CopyrightUrl: https://raw.githubusercontent.com/marticliment/UniGetUI/main/LICENSE
ShortDescription: User Interface to install packages from most common CLI package managers such as Winget, Scoop, Chocolatey, Pip, Npm, .NET Tool and PowerShell Gallery.
Description: |-
  The main goal of this project is to give a GUI Store to the most common CLI Package Managers for windows, such as Winget, Scoop, Chocolatey, Pip, Npm, .
  NET Tool and PowerShell Gallery.
  This app allows you to install, remove and maintain up-to-date the packages published on Winget, Scoop, Chocolatey, Pip, Npm, .
  NET Tool and PowerShell Gallery.
Moniker: unigetui
Tags:
- chocolatey
- dotnet-tool
- dotnet-tool-ui
- microsoft-store
- npm
- npm-ui
- open-source
- pip
- pip-ui
- powershell
- powershell-gallery
- scoop
- scoop-ui
- unigetui
- winget
- winget-ui
ReleaseNotes: |-
  Changelog
  - Fix a bug where installed packages showed duplicated
  - Fix a bug where phantom PowerShell 7.x updates would appear.
  - PowerShell 7.x will now show packages scoped for all users
  - Fix a bug where corrupt installOptions files wouldn't get properly overriden
  - Improve how single package selection is handled
  - Improvements to filtering panel resizing limits
  What's Changed
  - Clamp filters column width, collapse earlier by @Simek in #4107
  New Contributors
  - @Simek made their first contribution in #4107
  Full Changelog: 3.3.3...3.3.4
  UniGetUI.Installer.exe SHA256: 94F262C34B1E3B99E8EACA3DE129C793887A318DC2BFF21BBF2419DDF62E9BAD
  UniGetUI.x64.zip SHA256: E1E656574DB6AF34E6F53A8AA90BD4C3EA69DB5E795797E0E9919FA1E4AE6EFD
ReleaseNotesUrl: https://github.com/marticliment/UniGetUI/releases/tag/3.3.4
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://marticliment.com/unigetui/help/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
