# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MartiCliment.UniGetUI
PackageVersion: 3.3.4
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /NoAutoStart
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP- /NoAutoStart
  Interactive: /NORESTART /SP- /NoAutoStart
InstallerSuccessCodes:
- 1
UpgradeBehavior: install
ProductCode: '{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1'
ReleaseDate: 2025-09-12
AppsAndFeaturesEntries:
- DisplayName: UniGetUI
  ProductCode: '{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/marticliment/UniGetUI/releases/download/3.3.4/UniGetUI.Installer.exe
  InstallerSha256: 94F262C34B1E3B99E8EACA3DE129C793887A318DC2BFF21BBF2419DDF62E9BAD
  InstallerSwitches:
    Custom: /CURRENTUSER /NoWinGet
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/marticliment/UniGetUI/releases/download/3.3.4/UniGetUI.Installer.exe
  InstallerSha256: 94F262C34B1E3B99E8EACA3DE129C793887A318DC2BFF21BBF2419DDF62E9BAD
  InstallerSwitches:
    Custom: /ALLUSERS /NoWinGet
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\UniGetUI'
ManifestType: installer
ManifestVersion: 1.10.0
