# Created with WinGet Releaser v2 using Komac v1.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: SomePythonThings.WingetUIStore
PackageVersion: 1.6.5
PackageLocale: en-US
Publisher: Martí Climent
PublisherUrl: https://github.com/marticliment/WinGetUI
PublisherSupportUrl: https://github.com/marticliment/WinGetUI/issues
Author: Martí Climent
PackageName: WingetUI
PackageUrl: https://github.com/marticliment/WinGetUI
License: LGPL-2.1
LicenseUrl: https://raw.githubusercontent.com/marticliment/WinGetUI/main/LICENSE
Copyright: Copyright (C) 1991, 1999 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/marticliment/WinGetUI/main/LICENSE
ShortDescription: User Interface to install packages from most common CLI package managers such as Winget, Scoop and Chocolatey.
Description: |-
  The main goal of this project is to give a GUI Store to the most common CLI Package Managers for windows, such as Winget, Scoop and Chocolatey.
   This app allows you to install all the packages published on winget, scoop and appget.
Moniker: wingetui
Tags:
- chocolatey
- foss
- open-source
- scoop
- scoop-ui
- winget
- winget-ui
ReleaseNotes: |-
  Version 1.6.4 changelog
  - Fixed an issue where chocolatey packages were not loaded
  - Fixed issues whith ghost or missing packages in different circumstances
  - Using the parameter /NoAutoStart the installer will not launch WingetUI
  - Fixed an issue where selected packages wouldn't get installed at all
  - Fixed an issue where packages wouldn't be uninstallable from the updates section
  - Improved the context menu tooltip text.
    It now provides more information
  - Added Persian and Norwegian language
  - Fixed version not showing on the infobox.
  - Other minor improvements and bugfixes.
  - Added the ability to share packages:
  - Users wil be able to get a specific url for a package
  - This url will show a page with a button to launch WingetUI
  - WingetUI will launch with the infobox window on the specified package (if WingetUI is running on the system tray)
  - Live Demo:
ReleaseNotesUrl: https://github.com/marticliment/WingetUI/releases/tag/1.6.5
ManifestType: defaultLocale
ManifestVersion: 1.4.0
