# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: SomePythonThings.WingetUIStore
PackageVersion: 1.3.0.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2022-09-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/martinet101/WingetUI/releases/download/1.3.0.0/WingetUI.Installer.exe
  InstallerSha256: 99DD5008EE88E410E97710541CF59EBE94AFC5A81F1E6CBAE0B279ED298E2570
ManifestType: installer
ManifestVersion: 1.2.0
